name: Run tests
on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Build, Test, Lint: ${{ matrix.python-version }}'
        uses: chris48s/python-package-shared@main
        with:
          python-version: ${{ matrix.python-version }}
          pre-install: flit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  write-badges:
    needs: build
    uses: chris48s/python-package-shared/.github/workflows/write-badges-pep621.yml@main
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    with:
      build_result: ${{ needs.build.result }}
      package_dir: 'pip_abandoned'
